<?php
/**
 * AttachmentDisplayBodyMarketplaceSellerInfoTest
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  Klarna\Payments
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Klarna Payments API V1
 *
 * API spec
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.1.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Klarna\Payments\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * AttachmentDisplayBodyMarketplaceSellerInfoTest Class Doc Comment
 *
 * @category    Class
 * @description AttachmentDisplayBodyMarketplaceSellerInfo
 * @package     Klarna\Payments
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class AttachmentDisplayBodyMarketplaceSellerInfoTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "AttachmentDisplayBodyMarketplaceSellerInfo"
     */
    public function testAttachmentDisplayBodyMarketplaceSellerInfo()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "unique_account_identifier_seller"
     */
    public function testPropertyUniqueAccountIdentifierSeller()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sub_merchant_id"
     */
    public function testPropertySubMerchantId()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "product_category"
     */
    public function testPropertyProductCategory()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "product_name"
     */
    public function testPropertyProductName()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "account_registration_date"
     */
    public function testPropertyAccountRegistrationDate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "account_last_modified"
     */
    public function testPropertyAccountLastModified()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "seller_rating"
     */
    public function testPropertySellerRating()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "number_of_trades"
     */
    public function testPropertyNumberOfTrades()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "volume_of_trades"
     */
    public function testPropertyVolumeOfTrades()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
