<?php
/**
 * CustomerTokenCreationResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Klarna\Payments
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Klarna Payments API V1
 *
 * API spec
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Klarna\Payments;

use PHPUnit\Framework\TestCase;

/**
 * CustomerTokenCreationResponseTest Class Doc Comment
 *
 * @category    Class
 * @description CustomerTokenCreationResponse
 * @package     Klarna\Payments
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class CustomerTokenCreationResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CustomerTokenCreationResponse"
     */
    public function testCustomerTokenCreationResponse()
    {
    }

    /**
     * Test attribute "billing_address"
     */
    public function testPropertyBillingAddress()
    {
    }

    /**
     * Test attribute "customer"
     */
    public function testPropertyCustomer()
    {
    }

    /**
     * Test attribute "payment_method_reference"
     */
    public function testPropertyPaymentMethodReference()
    {
    }

    /**
     * Test attribute "redirect_url"
     */
    public function testPropertyRedirectUrl()
    {
    }

    /**
     * Test attribute "token_id"
     */
    public function testPropertyTokenId()
    {
    }
}
