<?php
/**
 * ErrorV2Test
 *
 * PHP version 5
 *
 * @category Class
 * @package  Klarna\Payments
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Klarna Payments API V1
 *
 * API spec
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Klarna\Payments;

use PHPUnit\Framework\TestCase;

/**
 * ErrorV2Test Class Doc Comment
 *
 * @category    Class
 * @description ErrorV2
 * @package     Klarna\Payments
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ErrorV2Test extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ErrorV2"
     */
    public function testErrorV2()
    {
    }

    /**
     * Test attribute "authorized_payment_method"
     */
    public function testPropertyAuthorizedPaymentMethod()
    {
    }

    /**
     * Test attribute "correlation_id"
     */
    public function testPropertyCorrelationId()
    {
    }

    /**
     * Test attribute "error_code"
     */
    public function testPropertyErrorCode()
    {
    }

    /**
     * Test attribute "error_messages"
     */
    public function testPropertyErrorMessages()
    {
    }

    /**
     * Test attribute "fraud_status"
     */
    public function testPropertyFraudStatus()
    {
    }

    /**
     * Test attribute "reason"
     */
    public function testPropertyReason()
    {
    }
}
