<?php
/**
 * MerchantSessionTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Klarna\Payments
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Klarna Payments API V1
 *
 * API spec
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Klarna\Payments;

use PHPUnit\Framework\TestCase;

/**
 * MerchantSessionTest Class Doc Comment
 *
 * @category    Class
 * @description MerchantSession
 * @package     Klarna\Payments
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class MerchantSessionTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "MerchantSession"
     */
    public function testMerchantSession()
    {
    }

    /**
     * Test attribute "client_token"
     */
    public function testPropertyClientToken()
    {
    }

    /**
     * Test attribute "payment_method_categories"
     */
    public function testPropertyPaymentMethodCategories()
    {
    }

    /**
     * Test attribute "session_id"
     */
    public function testPropertySessionId()
    {
    }
}
