<?php
/**
 * OptionsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Klarna\Payments
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Klarna Payments API V1
 *
 * API spec
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Klarna\Payments;

use PHPUnit\Framework\TestCase;

/**
 * OptionsTest Class Doc Comment
 *
 * @category    Class
 * @description Options
 * @package     Klarna\Payments
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class OptionsTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Options"
     */
    public function testOptions()
    {
    }

    /**
     * Test attribute "color_border"
     */
    public function testPropertyColorBorder()
    {
    }

    /**
     * Test attribute "color_border_selected"
     */
    public function testPropertyColorBorderSelected()
    {
    }

    /**
     * Test attribute "color_details"
     */
    public function testPropertyColorDetails()
    {
    }

    /**
     * Test attribute "color_text"
     */
    public function testPropertyColorText()
    {
    }

    /**
     * Test attribute "radius_border"
     */
    public function testPropertyRadiusBorder()
    {
    }
}
